"""bootstrap.py

One-command setup for the Ingresos tracker.
"""

import argparse
import subprocess
import sys
from datetime import date
from pathlib import Path

from dotenv import load_dotenv, set_key

from src.connectors.sheets import get_sheets_client

DEFAULT_SHEET_NAME = "Ingresos"
DEFAULT_START_DATE = date(2022, 1, 1)
ENV_FILE = ".env"
ENV_EXAMPLE = ".env.example"


def create_env_file() -> None:
    if Path(ENV_FILE).exists():
        return

    if Path(ENV_EXAMPLE).exists():
        print(f"Creating {ENV_FILE} from {ENV_EXAMPLE}...")
        Path(ENV_FILE).write_text(Path(ENV_EXAMPLE).read_text())
    else:
        print(f"Creating empty {ENV_FILE}...")
        Path(ENV_FILE).write_text(
            "# Auto-generated by bootstrap.py\n"
            "SPREADSHEET_ID=\n"
            "HISTORIC_START_DATE=2022-01-01\n"
        )


def get_or_create_spreadsheet(client, use_existing: str | None) -> tuple[str, str]:
    if use_existing:
        print(f"Using existing spreadsheet: {use_existing}")
        spreadsheet = client.open_by_key(use_existing)
        return spreadsheet.id, spreadsheet.url

    print(f"Creating new spreadsheet: {DEFAULT_SHEET_NAME!r}...")
    spreadsheet = client.create(DEFAULT_SHEET_NAME)
    print(f"Spreadsheet created: {spreadsheet.url}")
    return spreadsheet.id, spreadsheet.url


def update_env(key: str, value: str) -> None:
    env_path = Path(ENV_FILE)
    if not env_path.exists():
        create_env_file()
    set_key(env_path, key, value)
    print(f"{key} saved to {ENV_FILE}")


def run_command(cmd: list[str], description: str) -> None:
    print(f"\n{description}...")
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        print(f"Failed: {description}", file=sys.stderr)
        print(result.stderr, file=sys.stderr)
        sys.exit(1)
    print(result.stdout)
    print(f"{description} complete")


def main() -> None:
    parser = argparse.ArgumentParser(description="Bootstrap Ingresos tracker")
    parser.add_argument(
        "--use-existing",
        type=str,
        metavar="SPREADSHEET_ID",
        help="Use existing spreadsheet instead of creating new",
    )
    parser.add_argument(
        "--sheet-name",
        type=str,
        default=DEFAULT_SHEET_NAME,
        help=f"Name for new spreadsheet (default: {DEFAULT_SHEET_NAME!r})",
    )
    parser.add_argument(
        "--start-date",
        type=date.fromisoformat,
        default=DEFAULT_START_DATE,
        metavar="YYYY-MM-DD",
        help=f"Historical data start date (default: {DEFAULT_START_DATE})",
    )
    parser.add_argument(
        "--skip-fetch",
        action="store_true",
        help="Skip fetching historical data",
    )
    args = parser.parse_args()

    print("=" * 60)
    print("Ingresos Tracker - Bootstrap")
    print("=" * 60)

    create_env_file()
    load_dotenv()

    print("\n[1/5] Authenticating with Google...")
    try:
        client = get_sheets_client()
        print("Authentication successful")
    except FileNotFoundError as e:
        print(f"\n{e}", file=sys.stderr)
        print("\nPlease follow the instructions in OAUTH_SETUP.md", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"\nAuthentication failed: {e}", file=sys.stderr)
        sys.exit(1)

    print("\n[2/5] Setting up spreadsheet...")
    spreadsheet_id, spreadsheet_url = get_or_create_spreadsheet(
        client, args.use_existing
    )
    update_env("SPREADSHEET_ID", spreadsheet_id)
    update_env("HISTORIC_START_DATE", args.start_date.isoformat())

    load_dotenv(override=True)

    print("\n[3/5] Creating sheet structure...")
    run_command(
        ["uv", "run", "setup_sheet.py"],
        "Setup sheet structure",
    )

    if not args.skip_fetch:
        print("\n[4/5] Fetching all historical data (CER, CCL, REM)...")
        run_command(
            ["uv", "run", "fetch_data.py", "--since", args.start_date.isoformat()],
            f"Fetch all data since {args.start_date}",
        )
    else:
        print("\n[4/5] Skipping data fetch (--skip-fetch)")

    print("\n" + "=" * 60)
    print("Setup complete!")
    print("=" * 60)
    print(f"\nSpreadsheet URL: {spreadsheet_url}")
    print("\nNext steps:")
    print('  1. Open the "Ingresos" tab in your spreadsheet')
    print("  2. Fill in your monthly income data:")
    print("     - Column A: Fecha (first day of month, e.g., 01/06/2024)")
    print("     - Column B: Sueldo Bruto")
    print("     - Column G: SAC Bruto (only for Jun/Dec)")
    print("     - Columns I-K: Bonos, Comida, Viajes (optional)")
    print("  3. All formulas will auto-calculate!")
    print("\nTo update market data:")
    print("  ./update_daily.sh              # Manual update")
    print("  ./automation/install.sh        # Automatic daily updates (9 AM)")
    print()


if __name__ == "__main__":
    main()
