"""Estructura REORGANIZADA de la sheet Ingresos - Feb 2026."""

INCOME_GROUPS = [
    ("A", "A", ""),
    ("B", "F", "SUELDO"),
    ("G", "H", "AGUINALDO"),
    ("I", "I", "BONOS"),
    ("J", "K", "BENEFICIOS"),
    ("L", "L", "TOTAL"),
    ("M", "Q", "INFLACIÓN (CER)"),
    ("R", "Y", "VS ÚLTIMO AUMENTO ARS"),
    ("Z", "AG", "PROYECCIONES REM"),
    ("AH", "AM", "DÓLAR"),
    ("AN", "AT", "VS ÚLTIMO AUMENTO USD"),
]

INCOME_COLUMNS = [
    ("A", "Fecha", None),
    ("B", "Bruto", None),
    (
        "C",
        "Jubilacion",
        '=IF(OR(ISBLANK(B{r}), B{r}=0), "-", ROUND(B{r}*impuestos!$B$2,0))',
    ),
    ("D", "PAMI", '=IF(OR(ISBLANK(B{r}), B{r}=0), "-", ROUND(B{r}*impuestos!$B$3,0))'),
    (
        "E",
        "Obra Social",
        '=IF(OR(ISBLANK(B{r}), B{r}=0), "-", ROUND(B{r}*impuestos!$B$4,0))',
    ),
    ("F", "Neto", '=IF(OR(ISBLANK(B{r}), B{r}=0), "-", B{r}-C{r}-D{r}-E{r})'),
    ("G", "SAC Bruto", None),
    (
        "H",
        "SAC Neto",
        '=IF(OR(ISBLANK(G{r}), G{r}=0), "-", G{r}-ROUND(G{r}*impuestos!$B$2,0)-ROUND(G{r}*impuestos!$B$3,0)-ROUND(G{r}*impuestos!$B$4,0))',
    ),
    ("I", "Bono Neto", None),
    ("J", "Comida", None),
    ("K", "Otros Beneficios", None),
    (
        "L",
        "Total Neto",
        '=IF(OR(ISBLANK(F{r}), F{r}="-"), "-", IFERROR(IF(SUM(F{r}:K{r})=0, "-", SUM(F{r}:K{r})), "-"))',
    ),
    (
        "M",
        "Δ% CER MoM",
        '=IF(OR(ISBLANK(B{r}), B{r}=0), "-", IFERROR((VLOOKUP(A{r}, historic_data!$A$4:$B, 2, TRUE) / VLOOKUP(A{r-1}, historic_data!$A$4:$B, 2, TRUE)) - 1, "-"))',
    ),
    (
        "N",
        "Δ Bruto MoM",
        '=IF(OR(ISBLANK(B{r}), B{r}=0, ISBLANK(B{r-1})), "-", IFERROR(B{r}/B{r-1}-1,"-"))',
    ),
    (
        "O",
        "Poder Adq. Bruto MoM",
        '=IF(OR(M{r}="-", N{r}="-"), "-", IFERROR((1+N{r})/(1+M{r})-1,"-"))',
    ),
    (
        "P",
        "Δ Neto MoM",
        '=IF(OR(ISBLANK(B{r}), B{r}=0, ISBLANK(B{r-1})), "-", IFERROR(F{r}/F{r-1}-1,"-"))',
    ),
    (
        "Q",
        "Poder Adq. Neto MoM",
        '=IF(OR(M{r}="-", P{r}="-"), "-", IFERROR((1+P{r})/(1+M{r})-1,"-"))',
    ),
    (
        "R",
        "Bruto Base",
        '=IF(OR(ISBLANK(B{r}), B{r}=0), "-", IF(OR(ROW(B{r})=3, B{r}<>B{r-1}), B{r}, R{r-1}))',
    ),
    (
        "S",
        "Neto Base",
        '=IF(OR(ISBLANK(B{r}), B{r}=0), "-", IF(OR(ROW(B{r})=3, B{r}<>B{r-1}), F{r}, S{r-1}))',
    ),
    (
        "T",
        "CER Base",
        '=IF(OR(ISBLANK(B{r}), B{r}=0), "-", IF(OR(ROW(B{r})=3, B{r}<>B{r-1}), VLOOKUP(A{r}, historic_data!$A$4:$B, 2, TRUE), T{r-1}))',
    ),
    (
        "U",
        "Atraso Real (Bruto)",
        '=IF(OR(ISBLANK(B{r}), B{r}=0, T{r}="-"), "-", IFERROR((B{r}/R{r}) / (VLOOKUP(A{r}, historic_data!$A$4:$B, 2, TRUE)/T{r}) - 1, "-"))',
    ),
    (
        "V",
        "Paridad CER (Bruto)",
        '=IF(OR(ISBLANK(B{r}), B{r}=0, T{r}="-"), "-", IFERROR(R{r} * (VLOOKUP(A{r}, historic_data!$A$4:$B, 2, TRUE)/T{r}), "-"))',
    ),
    (
        "W",
        "Atraso Real (Neto)",
        '=IF(OR(ISBLANK(B{r}), B{r}=0, T{r}="-"), "-", IFERROR((F{r}/S{r}) / (VLOOKUP(A{r}, historic_data!$A$4:$B, 2, TRUE)/T{r}) - 1, "-"))',
    ),
    (
        "X",
        "Paridad CER (Neto)",
        '=IF(OR(ISBLANK(B{r}), B{r}=0, T{r}="-"), "-", IFERROR(S{r} * (VLOOKUP(A{r}, historic_data!$A$4:$B, 2, TRUE)/T{r}), "-"))',
    ),
    ("Y", "Poder Adq. vs Aumento", "=W{r}"),
    (
        "Z",
        "REM 3m (%)",
        '=IF(OR(ISBLANK(B{r}), B{r}=0), "-", (1+IFERROR(VLOOKUP($A{r}, REM!$A$4:$I, 3, FALSE), 0))*(1+IFERROR(VLOOKUP($A{r}, REM!$A$4:$I, 4, FALSE), 0))*(1+IFERROR(VLOOKUP($A{r}, REM!$A$4:$I, 5, FALSE), 0))-1)',
    ),
    ("AA", "Objetivo 3m Bruto", '=IF(Z{r}="-", "-", IFERROR(B{r} * (1+Z{r}), "-"))'),
    ("AB", "Objetivo 3m Neto", '=IF(Z{r}="-", "-", IFERROR(F{r} * (1+Z{r}), "-"))'),
    ("AC", "Δ 3m (%)", "=Z{r}"),
    (
        "AD",
        "REM 6m (%)",
        '=IF(OR(ISBLANK(B{r}), B{r}=0), "-", (1+Z{r})*(1+IFERROR(VLOOKUP($A{r}, REM!$A$4:$I, 6, FALSE), 0))*(1+IFERROR(VLOOKUP($A{r}, REM!$A$4:$I, 7, FALSE), 0))*(1+IFERROR(VLOOKUP($A{r}, REM!$A$4:$I, 8, FALSE), 0))-1)',
    ),
    ("AE", "Objetivo 6m Bruto", '=IF(AD{r}="-", "-", IFERROR(B{r} * (1+AD{r}), "-"))'),
    ("AF", "Objetivo 6m Neto", '=IF(AD{r}="-", "-", IFERROR(F{r} * (1+AD{r}), "-"))'),
    ("AG", "Δ 6m (%)", "=AD{r}"),
    (
        "AH",
        "CCL",
        '=IF(OR(ISBLANK(B{r}), B{r}=0), "-", IFERROR(INDEX(FILTER(historic_data!$C$4:$C, historic_data!$C$4:$C <> ""), MATCH(A{r}, FILTER(historic_data!$A$4:$A, historic_data!$C$4:$C <> ""), 1)), "-"))',
    ),
    (
        "AI",
        "Δ % CCL MoM",
        '=IF(OR(AH{r}="-", AH{r-1}="-"), "-", IFERROR((AH{r}-AH{r-1})/AH{r-1}, "-"))',
    ),
    ("AJ", "Sueldo USD Bruto", '=IF(OR(B{r}=0, AH{r}="-"), "-", IFERROR(B{r}/AH{r},"-"))'),
    ("AK", "Sueldo USD Neto", '=IF(OR(F{r}="-", AH{r}="-"), "-", IFERROR(F{r}/AH{r},"-"))'),
    (
        "AL",
        "Poder Adq. MoM (USD) Bruto",
        '=IF(OR(AJ{r}="-", AJ{r-1}="-"), "-", IFERROR((AJ{r}/AJ{r-1})-1, "-"))',
    ),
    (
        "AM",
        "Poder Adq. MoM (USD) Neto",
        '=IF(OR(AK{r}="-", AK{r-1}="-"), "-", IFERROR((AK{r}/AK{r-1})-1, "-"))',
    ),
    (
        "AN",
        "CCL Base",
        '=IF(OR(ISBLANK(B{r}), B{r}=0), "-", IF(OR(ROW(B{r})=3, B{r}<>B{r-1}), AH{r}, AN{r-1}))',
    ),
    (
        "AO",
        "Sueldo USD Bruto Base",
        '=IF(OR(ISBLANK(B{r}), B{r}=0), "-", IF(OR(ROW(B{r})=3, B{r}<>B{r-1}), AJ{r}, AO{r-1}))',
    ),
    (
        "AP",
        "Sueldo USD Neto Base",
        '=IF(OR(ISBLANK(B{r}), B{r}=0), "-", IF(OR(ROW(B{r})=3, B{r}<>B{r-1}), AK{r}, AP{r-1}))',
    ),
    (
        "AQ",
        "Atraso USD (Bruto)",
        '=IF(OR(AJ{r}="-", AO{r}="-"), "-", IFERROR((AJ{r}/AO{r})-1, "-"))',
    ),
    (
        "AR",
        "Paridad USD (Bruto)",
        '=IF(OR(R{r}="-", AH{r}="-", AN{r}="-"), "-", IFERROR(R{r} * (AH{r}/AN{r}), "-"))',
    ),
    (
        "AS",
        "Atraso USD (Neto)",
        '=IF(OR(AK{r}="-", AP{r}="-"), "-", IFERROR((AK{r}/AP{r})-1, "-"))',
    ),
    (
        "AT",
        "Paridad USD (Neto)",
        '=IF(OR(S{r}="-", AH{r}="-", AN{r}="-"), "-", IFERROR(S{r} * (AH{r}/AN{r}), "-"))',
    ),
]

COLUMN_FORMATS = {
    "A": {"type": "DATE", "pattern": "dd/mm/yyyy"},
    "B": {"type": "CURRENCY", "pattern": "$#,##0"},
    "C": {"type": "CURRENCY", "pattern": "$#,##0"},
    "D": {"type": "CURRENCY", "pattern": "$#,##0"},
    "E": {"type": "CURRENCY", "pattern": "$#,##0"},
    "F": {"type": "CURRENCY", "pattern": "$#,##0"},
    "G": {"type": "CURRENCY", "pattern": "$#,##0"},
    "H": {"type": "CURRENCY", "pattern": "$#,##0"},
    "I": {"type": "CURRENCY", "pattern": "$#,##0"},
    "J": {"type": "CURRENCY", "pattern": "$#,##0"},
    "K": {"type": "CURRENCY", "pattern": "$#,##0"},
    "L": {"type": "CURRENCY", "pattern": "$#,##0"},
    "M": {"type": "PERCENT", "pattern": "0.00%"},
    "N": {"type": "PERCENT", "pattern": "0.00%"},
    "O": {"type": "PERCENT", "pattern": "0.00%"},
    "P": {"type": "PERCENT", "pattern": "0.00%"},
    "Q": {"type": "PERCENT", "pattern": "0.00%"},
    "R": {"type": "NUMBER", "pattern": "#,##0"},
    "S": {"type": "NUMBER", "pattern": "#,##0"},
    "T": {"type": "NUMBER", "pattern": "0.0000"},
    "U": {"type": "PERCENT", "pattern": "0.00%"},
    "V": {"type": "CURRENCY", "pattern": "$#,##0"},
    "W": {"type": "PERCENT", "pattern": "0.00%"},
    "X": {"type": "CURRENCY", "pattern": "$#,##0"},
    "Y": {"type": "PERCENT", "pattern": "0.00%"},
    "Z": {"type": "PERCENT", "pattern": "0.00%"},
    "AA": {"type": "CURRENCY", "pattern": "$#,##0"},
    "AB": {"type": "CURRENCY", "pattern": "$#,##0"},
    "AC": {"type": "PERCENT", "pattern": "0.00%"},
    "AD": {"type": "PERCENT", "pattern": "0.00%"},
    "AE": {"type": "CURRENCY", "pattern": "$#,##0"},
    "AF": {"type": "CURRENCY", "pattern": "$#,##0"},
    "AG": {"type": "PERCENT", "pattern": "0.00%"},
    "AH": {"type": "CURRENCY", "pattern": "$#,##0.00"},
    "AI": {"type": "PERCENT", "pattern": "0.00%"},
    "AJ": {"type": "NUMBER", "pattern": "#,##0.00"},
    "AK": {"type": "NUMBER", "pattern": "#,##0.00"},
    "AL": {"type": "PERCENT", "pattern": "0.00%"},
    "AM": {"type": "PERCENT", "pattern": "0.00%"},
    "AN": {"type": "CURRENCY", "pattern": "$#,##0.00"},
    "AO": {"type": "NUMBER", "pattern": "#,##0.00"},
    "AP": {"type": "NUMBER", "pattern": "#,##0.00"},
    "AQ": {"type": "PERCENT", "pattern": "0.00%"},
    "AR": {"type": "CURRENCY", "pattern": "$#,##0"},
    "AS": {"type": "PERCENT", "pattern": "0.00%"},
    "AT": {"type": "CURRENCY", "pattern": "$#,##0"},
}

COLUMN_DESCRIPTIONS = {
    "A": "Fecha del registro mensual",
    "B": "Sueldo bruto mensual (input manual)",
    "C": "Descuento jubilación (11% del bruto)",
    "D": "Descuento PAMI (3% del bruto)",
    "E": "Descuento obra social (3% del bruto)",
    "F": "Sueldo neto (bruto - descuentos)",
    "G": "Aguinaldo bruto (input manual)",
    "H": "Aguinaldo neto (SAC - descuentos)",
    "I": "Bonos extraordinarios netos (input manual)",
    "J": "Beneficio de comida mensual (input manual)",
    "K": "Otros beneficios (input manual)",
    "L": "Total neto mensual (suma de todo)",
    "M": "Inflación del mes (CER)",
    "N": "Variación nominal de sueldo bruto",
    "O": "Poder adquisitivo ganado/perdido en el mes (Bruto)",
    "P": "Variación nominal de sueldo neto",
    "Q": "Poder adquisitivo ganado/perdido en el mes (Neto)",
    "R": "Bruto al momento del último aumento",
    "S": "Neto al momento del último aumento",
    "T": "Valor CER al momento del último aumento",
    "U": "% de atraso real vs inflación desde último aumento (Bruto)",
    "V": "Sueldo bruto para mantener paridad CER",
    "W": "% de atraso real vs inflación desde último aumento (Neto)",
    "X": "Sueldo neto para mantener paridad CER",
    "Y": "Poder adquisitivo vs último aumento (Neto vs CER)",
    "Z": "Inflación proyectada REM 3m",
    "AA": "Sueldo bruto objetivo para dentro de 3 meses",
    "AB": "Sueldo neto objetivo para dentro de 3 meses",
    "AC": "% de aumento sugerido hoy para cubrir los próximos 3 meses",
    "AD": "Inflación proyectada REM 6m",
    "AE": "Sueldo bruto objetivo para dentro de 6 meses",
    "AF": "Sueldo neto objetivo para dentro de 6 meses",
    "AG": "% de aumento sugerido hoy para cubrir los próximos 6 meses",
    "AH": "Dólar CCL cierre de mes",
    "AI": "Variación % CCL MoM",
    "AJ": "Sueldo Bruto en USD CCL",
    "AK": "Sueldo Neto en USD CCL",
    "AL": "Poder adquisitivo ganado/perdido en USD MoM (Bruto)",
    "AM": "Poder adquisitivo ganado/perdido en USD MoM (Neto)",
    "AN": "CCL al momento del último aumento",
    "AO": "Sueldo Bruto USD al momento del último aumento",
    "AP": "Sueldo Neto USD al momento del último aumento",
    "AQ": "% de caída/subida en USD desde último aumento (Bruto)",
    "AR": "Sueldo en ARS para recuperar Bruto USD del aumento",
    "AS": "% de caída/subida en USD desde último aumento (Neto)",
    "AT": "Sueldo en ARS para recuperar Neto USD del aumento",
}

IMPUESTOS_ROWS = [
    ("Jubilacion", 0.11, "Ley 24241"),
    ("PAMI", 0.03, "Ley 19032"),
    ("Obra Social", 0.03, "Ley 23660"),
    ("Otro", 0.00, "—"),
]

HISTORIC_VARIABLES = [
    (None, "Fecha", None),
    (30, "CER", "CER"),
    ("IOL/dolarapi", "CCL", "CCL"),
]
