"""Estructura OPTIMIZADA de la sheet Ingresos - Feb 2026."""

INCOME_GROUPS = [
    ("A", "A", "PERIODO"),
    ("B", "G", "SUELDO"),
    ("H", "I", "AGUINALDO"),
    ("J", "J", "BONOS"),
    ("K", "L", "BENEFICIOS"),
    ("M", "M", "TOTAL"),
    ("N", "S", "COMPARACION CON ULTIMO AUMENTO ARS"),
    ("T", "W", "INFLACIÓN (CER)"),
    ("X", "AC", "PROYECCION REM"),
    ("AD", "AG", "DÓLAR"),
    ("AH", "AM", "VS ÚLTIMO AUMENTO USD"),
]

INCOME_COLUMNS = [
    ("A", "Periodo Abonado", None),
    ("B", "Fecha", None),
    ("C", "Bruto", None),
    (
        "D",
        "Jubilacion",
        '=IF(OR(ISBLANK(C{r}), C{r}=0), "-", ROUND(C{r}*impuestos!$B$2,0))',
    ),
    ("E", "PAMI", '=IF(OR(ISBLANK(C{r}), C{r}=0), "-", ROUND(C{r}*impuestos!$B$3,0))'),
    (
        "F",
        "Obra Social",
        '=IF(OR(ISBLANK(C{r}), C{r}=0), "-", ROUND(C{r}*impuestos!$B$4,0))',
    ),
    ("G", "Neto", '=IF(OR(ISBLANK(C{r}), C{r}=0), "-", C{r}-D{r}-E{r}-F{r})'),
    ("H", "SAC Bruto", None),
    (
        "I",
        "SAC Neto",
        '=IF(OR(ISBLANK(H{r}), H{r}=0), "-", H{r}-ROUND(H{r}*impuestos!$B$2,0)-ROUND(H{r}*impuestos!$B$3,0)-ROUND(H{r}*impuestos!$B$4,0))',
    ),
    ("J", "Bono Neto", None),
    ("K", "Comida", None),
    ("L", "Otros Beneficios", None),
    (
        "M",
        "Total Neto",
        '=IF(OR(ISBLANK(G{r}), G{r}="-"), "-", IFERROR(IF(SUM(G{r}:L{r})=0, "-", SUM(G{r}:L{r})), "-"))',
    ),
    (
        "N",
        "Bruto Base",
        '=IF(OR(ISBLANK(C{r}), C{r}=0), "-", IF(OR(ROW(C{r})=3, C{r}<>C{r-1}), C{r}, N{r-1}))',
    ),
    (
        "O",
        "Neto Base",
        '=IF(OR(ISBLANK(C{r}), C{r}=0), "-", IF(OR(ROW(C{r})=3, C{r}<>C{r-1}), G{r}, O{r-1}))',
    ),
    (
        "P",
        "CER Base",
        '=IF(OR(ISBLANK(C{r}), C{r}=0), "-", IF(OR(ROW(C{r})=3, C{r}<>C{r-1}), VLOOKUP(EOMONTH(A{r}, 0), historic_data!$A$4:$B, 2, TRUE), P{r-1}))',
    ),
    (
        "Q",
        "Paridad CER (Bruto)",
        '=IF(OR(ISBLANK(C{r}), C{r}=0, P{r}="-"), "-", IFERROR(N{r} * (VLOOKUP(EOMONTH(A{r}, 0), historic_data!$A$4:$B, 2, TRUE)/P{r}), "-"))',
    ),
    (
        "R",
        "Paridad CER (Neto)",
        '=IF(OR(ISBLANK(C{r}), C{r}=0, P{r}="-"), "-", IFERROR(O{r} * (VLOOKUP(EOMONTH(A{r}, 0), historic_data!$A$4:$B, 2, TRUE)/P{r}), "-"))',
    ),
    (
        "S",
        "Poder Adq. vs Aumento",
        '=IF(OR(ISBLANK(C{r}), C{r}=0, P{r}="-"), "-", IFERROR((G{r}/O{r}) / (VLOOKUP(EOMONTH(A{r}, 0), historic_data!$A$4:$B, 2, TRUE)/P{r}) - 1, "-"))',
    ),
    (
        "T",
        "Δ% CER MoM",
        '=IF(OR(ISBLANK(C{r}), C{r}=0), "-", IFERROR((VLOOKUP(EOMONTH(A{r}, 0), historic_data!$A$4:$B, 2, TRUE) / VLOOKUP(EOMONTH(A{r-1}, 0), historic_data!$A$4:$B, 2, TRUE)) - 1, "-"))',
    ),
    (
        "U",
        "Gap REM 3m",
        '=IFERROR(T{r} - VLOOKUP(EOMONTH(OFFSET(A{r}, -3, 0), 0), REM!$A:$I, 5, FALSE), "-")',
    ),
    (
        "V",
        "Gap REM 6m",
        '=IFERROR(T{r} - VLOOKUP(EOMONTH(OFFSET(A{r}, -6, 0), 0), REM!$A:$I, 8, FALSE), "-")',
    ),
    (
        "W",
        "Poder Adquisitivo MoM",
        '=IF(OR(T{r}="-", ISBLANK(G{r}), ISBLANK(G{r-1}), G{r}=0, G{r-1}=0), "-", IFERROR((G{r}/G{r-1})/(1+T{r})-1,"-"))',
    ),
    (
        "X",
        "REM 3m (%)",
        '=IF(OR(ISBLANK(C{r}), C{r}=0), "-", (1+IFERROR(VLOOKUP(EOMONTH(A{r}, 0), REM!$A$4:$I, 3, FALSE), 0))*(1+IFERROR(VLOOKUP(EOMONTH(A{r}, 0), REM!$A$4:$I, 4, FALSE), 0))*(1+IFERROR(VLOOKUP(EOMONTH(A{r}, 0), REM!$A$4:$I, 5, FALSE), 0))-1)',
    ),
    ("Y", "Objetivo 3m Bruto", '=IF(X{r}="-", "-", IFERROR(C{r} * (1+X{r}), "-"))'),
    ("Z", "Objetivo 3m Neto", '=IF(X{r}="-", "-", IFERROR(G{r} * (1+X{r}), "-"))'),
    (
        "AA",
        "REM 6m (%)",
        '=IF(OR(ISBLANK(C{r}), C{r}=0), "-", (1+X{r})*(1+IFERROR(VLOOKUP(EOMONTH(A{r}, 0), REM!$A$4:$I, 6, FALSE), 0))*(1+IFERROR(VLOOKUP(EOMONTH(A{r}, 0), REM!$A$4:$I, 7, FALSE), 0))*(1+IFERROR(VLOOKUP(EOMONTH(A{r}, 0), REM!$A$4:$I, 8, FALSE), 0))-1)',
    ),
    ("AB", "Objetivo 6m Bruto", '=IF(AA{r}="-", "-", IFERROR(C{r} * (1+AA{r}), "-"))'),
    ("AC", "Objetivo 6m Neto", '=IF(AA{r}="-", "-", IFERROR(G{r} * (1+AA{r}), "-"))'),
    (
        "AD",
        "CCL",
        '=IF(OR(ISBLANK(C{r}), C{r}=0), "-", IFERROR(INDEX(FILTER(historic_data!$C$4:$C, historic_data!$C$4:$C <> ""), MATCH(B{r}, FILTER(historic_data!$A$4:$A, historic_data!$C$4:$C <> ""), 1)), "-"))',
    ),
    (
        "AE",
        "Δ % CCL MoM",
        '=IF(AD{r}="-", "-", IFERROR((AD{r} - INDEX(FILTER(historic_data!$C$4:$C, historic_data!$C$4:$C <> ""), MATCH(EOMONTH(B{r}, -1), FILTER(historic_data!$A$4:$A, historic_data!$C$4:$C <> ""), 1))) / INDEX(FILTER(historic_data!$C$4:$C, historic_data!$C$4:$C <> ""), MATCH(EOMONTH(B{r}, -1), FILTER(historic_data!$A$4:$A, historic_data!$C$4:$C <> ""), 1)), "-"))',
    ),
    (
        "AF",
        "Sueldo USD Bruto",
        '=IF(OR(C{r}=0, AD{r}="-"), "-", IFERROR(C{r}/AD{r},"-"))',
    ),
    (
        "AG",
        "Sueldo USD Neto",
        '=IF(OR(G{r}="-", AD{r}="-"), "-", IFERROR(G{r}/AD{r},"-"))',
    ),
    (
        "AH",
        "CCL Base",
        '=IF(OR(ISBLANK(C{r}), C{r}=0), "-", IF(OR(ROW(C{r})=3, C{r}<>C{r-1}), AD{r}, AH{r-1}))',
    ),
    (
        "AI",
        "Sueldo USD Bruto Base",
        '=IF(OR(ISBLANK(C{r}), C{r}=0), "-", IF(OR(ROW(C{r})=3, C{r}<>C{r-1}), AF{r}, AI{r-1}))',
    ),
    (
        "AJ",
        "Sueldo USD Neto Base",
        '=IF(OR(ISBLANK(C{r}), C{r}=0), "-", IF(OR(ROW(C{r})=3, C{r}<>C{r-1}), AG{r}, AJ{r-1}))',
    ),
    (
        "AK",
        "Paridad USD (Bruto)",
        '=IF(OR(N{r}="-", AD{r}="-", AH{r}="-"), "-", IFERROR(N{r} * (AD{r}/AH{r}), "-"))',
    ),
    (
        "AL",
        "Paridad USD (Neto)",
        '=IF(OR(O{r}="-", AD{r}="-", AH{r}="-"), "-", IFERROR(O{r} * (AD{r}/AH{r}), "-"))',
    ),
    (
        "AM",
        "Atraso USD",
        '=IF(OR(AG{r}="-", AJ{r}="-"), "-", IFERROR((AG{r}/AJ{r})-1, "-"))',
    ),
]

COLUMN_FORMATS = {
    "A": {"type": "DATE", "pattern": "mmm-yy"},
    "B": {"type": "DATE", "pattern": "dd/mm/yyyy"},
    "C": {"type": "CURRENCY", "pattern": "$#,##0"},
    "D": {"type": "CURRENCY", "pattern": "$#,##0"},
    "E": {"type": "CURRENCY", "pattern": "$#,##0"},
    "F": {"type": "CURRENCY", "pattern": "$#,##0"},
    "G": {"type": "CURRENCY", "pattern": "$#,##0"},
    "H": {"type": "CURRENCY", "pattern": "$#,##0"},
    "I": {"type": "CURRENCY", "pattern": "$#,##0"},
    "J": {"type": "CURRENCY", "pattern": "$#,##0"},
    "K": {"type": "CURRENCY", "pattern": "$#,##0"},
    "L": {"type": "CURRENCY", "pattern": "$#,##0"},
    "M": {"type": "CURRENCY", "pattern": "$#,##0"},
    "N": {"type": "NUMBER", "pattern": "#,##0"},
    "O": {"type": "NUMBER", "pattern": "#,##0"},
    "P": {"type": "NUMBER", "pattern": "0.0000"},
    "Q": {"type": "CURRENCY", "pattern": "$#,##0"},
    "R": {"type": "CURRENCY", "pattern": "$#,##0"},
    "S": {"type": "PERCENT", "pattern": "0.00%"},
    "T": {"type": "PERCENT", "pattern": "0.00%"},
    "U": {"type": "PERCENT", "pattern": "0.00%"},
    "V": {"type": "PERCENT", "pattern": "0.00%"},
    "W": {"type": "PERCENT", "pattern": "0.00%"},
    "X": {"type": "PERCENT", "pattern": "0.00%"},
    "Y": {"type": "CURRENCY", "pattern": "$#,##0"},
    "Z": {"type": "CURRENCY", "pattern": "$#,##0"},
    "AA": {"type": "PERCENT", "pattern": "0.00%"},
    "AB": {"type": "CURRENCY", "pattern": "$#,##0"},
    "AC": {"type": "CURRENCY", "pattern": "$#,##0"},
    "AD": {"type": "CURRENCY", "pattern": "$#,##0.00"},
    "AE": {"type": "PERCENT", "pattern": "0.00%"},
    "AF": {"type": "NUMBER", "pattern": "#,##0.00"},
    "AG": {"type": "NUMBER", "pattern": "#,##0.00"},
    "AH": {"type": "CURRENCY", "pattern": "$#,##0.00"},
    "AI": {"type": "NUMBER", "pattern": "#,##0.00"},
    "AJ": {"type": "NUMBER", "pattern": "#,##0.00"},
    "AK": {"type": "CURRENCY", "pattern": "$#,##0"},
    "AL": {"type": "CURRENCY", "pattern": "$#,##0"},
    "AM": {"type": "PERCENT", "pattern": "0.00%"},
}

COLUMN_DESCRIPTIONS = {
    "A": "Periodo al que corresponde el sueldo",
    "B": "Fecha real de cobro",
    "C": "Sueldo bruto mensual (input manual)",
    "D": "Descuento jubilación (11% del bruto)",
    "E": "Descuento PAMI (3% del bruto)",
    "F": "Descuento obra social (3% del bruto)",
    "G": "Sueldo neto (bruto - descuentos)",
    "H": "Aguinaldo bruto (input manual)",
    "I": "Aguinaldo neto (SAC - descuentos)",
    "J": "Bonos extraordinarios netos (input manual)",
    "K": "Beneficio de comida mensual (input manual)",
    "L": "Otros beneficios (input manual)",
    "M": "Total neto mensual (suma de todo)",
    "N": "Bruto al momento del último aumento",
    "O": "Neto al momento del último aumento",
    "P": "Valor CER al momento del último aumento",
    "Q": "Sueldo bruto para mantener paridad CER",
    "R": "Sueldo neto para mantener paridad CER",
    "S": "Poder adquisitivo acumulado vs último aumento",
    "T": "Inflación del mes (CER)",
    "U": "Diferencia entre inflación real y proyección REM de hace 3 meses",
    "V": "Diferencia entre inflación real y proyección REM de hace 6 meses",
    "W": "Poder adquisitivo ganado/perdido en el mes",
    "X": "Inflación proyectada REM 3m",
    "Y": "Sueldo bruto objetivo para dentro de 3 meses",
    "Z": "Sueldo neto objetivo para dentro de 3 meses",
    "AA": "Inflación proyectada REM 6m",
    "AB": "Sueldo bruto objetivo para dentro de 6 meses",
    "AC": "Sueldo neto objetivo para dentro de 6 meses",
    "AD": "Dólar CCL cierre de mes",
    "AE": "Variación % CCL MoM",
    "AF": "Sueldo Bruto en USD CCL",
    "AG": "Sueldo Neto en USD CCL",
    "AH": "CCL al momento del último aumento",
    "AI": "Sueldo Bruto USD al momento del último aumento",
    "AJ": "Sueldo Neto USD al momento del último aumento",
    "AK": "Sueldo en ARS para recuperar Bruto USD del aumento",
    "AL": "Sueldo en ARS para recuperar Neto USD del aumento",
    "AM": "Atraso real en USD vs último aumento",
}

IMPUESTOS_ROWS = [
    ("Jubilacion", 0.11, "Ley 24241"),
    ("PAMI", 0.03, "Ley 19032"),
    ("Obra Social", 0.03, "Ley 23660"),
    ("Otro", 0.00, "—"),
]

HISTORIC_VARIABLES = [
    (None, "Fecha", None),
    (30, "CER", "CER"),
    ("IOL/dolarapi", "CCL", "CCL"),
    ("yfinance", "SPY", "SPY"),
]
